-- ═══════════════════════════════════════════════════════════════════════
-- Audema — Combined Supabase Schema
-- Run this ONCE in: Supabase Dashboard → SQL Editor → New query → Run
--
-- This concatenates every supabase-*.sql migration in this repo, in
-- dependency order (each section still notes what it requires, for
-- reference — that ordering is already satisfied by running top to
-- bottom). The individual supabase-*.sql files remain the source of
-- truth for future changes; this combined file is a convenience for a
-- single manual paste and is regenerated by concatenating them, not
-- hand-maintained separately.
--
-- Order:
--   1. supabase-business-brain.sql
--   2. supabase-intelligence-profiles.sql
--   3. supabase-social-posts.sql
--   4. supabase-credits.sql
--   5. supabase-audience.sql
--   6. supabase-audience-consent.sql
--   7. supabase-ab-testing.sql
--   8. supabase-agent-audits.sql
--   9. supabase-competitor-watch.sql
--  10. supabase-billing.sql
-- ═══════════════════════════════════════════════════════════════════════


-- ═══════════════════════════════════════════════════════════════════════
-- ⚠️  DESTRUCTIVE — CLEAR EXISTING TABLES BEFORE IMPORT
-- ═══════════════════════════════════════════════════════════════════════
-- Drops every table the migrations below create, so the CREATE TABLE
-- statements that follow build a genuinely clean copy instead of
-- upserting onto whatever is already there. CASCADE also removes any
-- indexes, triggers, and RLS policies attached to these tables.
--
-- This ONLY touches tables this file creates — it never touches
-- auth.users, projects, or anything else already in your database.
--
-- ⚠️  THIS PERMANENTLY DELETES ALL DATA IN THESE TABLES. There is no
-- undo. If any of them already hold real data you care about, back it
-- up first (Supabase Dashboard → Database → Backups, or pg_dump) —
-- comment out this block instead of running it if you're unsure.
-- ═══════════════════════════════════════════════════════════════════════

DROP TABLE IF EXISTS competitor_changes         CASCADE;
DROP TABLE IF EXISTS competitor_snapshots       CASCADE;
DROP TABLE IF EXISTS competitor_watches         CASCADE;
DROP TABLE IF EXISTS agent_audit_findings       CASCADE;
DROP TABLE IF EXISTS agent_audit_runs           CASCADE;
DROP TABLE IF EXISTS conversions                CASCADE;
DROP TABLE IF EXISTS visitors                   CASCADE;
DROP TABLE IF EXISTS goals                      CASCADE;
DROP TABLE IF EXISTS variants                   CASCADE;
DROP TABLE IF EXISTS experiments                CASCADE;
DROP TABLE IF EXISTS campaign_sends              CASCADE;
DROP TABLE IF EXISTS segment_members            CASCADE;
DROP TABLE IF EXISTS segments                   CASCADE;
DROP TABLE IF EXISTS contacts                   CASCADE;
DROP TABLE IF EXISTS credit_balances            CASCADE;
DROP TABLE IF EXISTS social_posts               CASCADE;
DROP TABLE IF EXISTS intelligence_profile_members CASCADE;
DROP TABLE IF EXISTS intelligence_profiles      CASCADE;
DROP TABLE IF EXISTS business_brain_history     CASCADE;
DROP TABLE IF EXISTS business_brain             CASCADE;

-- ═══════════════════════════════════════════════════════════════════════
-- END destructive block — fresh CREATE statements start below
-- ═══════════════════════════════════════════════════════════════════════


-- ═══════════════════════════════════════════════════════════════════════
-- SOURCE: supabase-business-brain.sql
-- ═══════════════════════════════════════════════════════════════════════

-- Aduma Business Brain — Per-Project Cloud Sync + Version History
-- Run this in: Supabase Dashboard → SQL Editor → New query → Run
--
-- Fixes: BusinessBrain data previously lived only in localStorage (key
-- 'intel_business_brain'), was NOT scoped per-project (one shared brain for
-- every project), and had zero version history. This schema makes Business
-- Brain a first-class per-project, cloud-synced, versioned record.

-- ── Current brain state (one row per project) ─────────────────────────────
CREATE TABLE IF NOT EXISTS business_brain (
  id                UUID        DEFAULT uuid_generate_v4() PRIMARY KEY,
  project_id        UUID        NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  user_id           UUID        NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  data              JSONB       NOT NULL DEFAULT '{}',
  confidence_score  INTEGER     DEFAULT 0,
  created_at        TIMESTAMPTZ DEFAULT NOW(),
  updated_at        TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE (project_id)
);

-- ── Append-only snapshot history (last 20 kept per project, pruned by app) ─
CREATE TABLE IF NOT EXISTS business_brain_history (
  id                UUID        DEFAULT uuid_generate_v4() PRIMARY KEY,
  project_id        UUID        NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  user_id           UUID        NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  data              JSONB       NOT NULL,
  confidence_score  INTEGER     DEFAULT 0,
  label             TEXT,                 -- e.g. 'Autosave', 'Autofill overwrite', 'Manual snapshot'
  created_at        TIMESTAMPTZ DEFAULT NOW()
);

-- ── Indexes ─────────────────────────────────────────────────────────────────
CREATE INDEX IF NOT EXISTS idx_brain_project          ON business_brain         (project_id);
CREATE INDEX IF NOT EXISTS idx_brain_user             ON business_brain         (user_id);
CREATE INDEX IF NOT EXISTS idx_brain_history_project   ON business_brain_history (project_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_brain_history_user      ON business_brain_history (user_id);

-- ── Row-Level Security ────────────────────────────────────────────────────
ALTER TABLE business_brain         ENABLE ROW LEVEL SECURITY;
ALTER TABLE business_brain_history ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users manage own brain"
  ON business_brain FOR ALL
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users manage own brain history"
  ON business_brain_history FOR ALL
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

-- ── updated_at trigger ────────────────────────────────────────────────────
CREATE OR REPLACE FUNCTION update_business_brain_updated_at()
RETURNS TRIGGER AS $$
BEGIN NEW.updated_at = NOW(); RETURN NEW; END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER business_brain_updated_at
  BEFORE UPDATE ON business_brain
  FOR EACH ROW EXECUTE FUNCTION update_business_brain_updated_at();


-- ═══════════════════════════════════════════════════════════════════════
-- SOURCE: supabase-intelligence-profiles.sql
-- ═══════════════════════════════════════════════════════════════════════

-- Audema Intelligence Profiles — multi-business Intelligence Layer
-- Run this in: Supabase Dashboard → SQL Editor → New query → Run
-- Requires: supabase-business-brain.sql has already been run.
--
-- One "intelligence profile" = one business's complete Intelligence Layer
-- (Business Brain, and later radar/pulse). Users switch profiles to work on
-- different businesses. Plan limits (see get_intel_profile_limit below):
-- start/growth/scale/autonomous=1, enterprise=admin-configured,
-- agency_starter=5, agency_growth=15, agency_pro=50, agency_enterprise=admin-configured.

-- ── Extend account plans ───────────────────────────────────────────────────
-- Canonical plan enum, matching Audema's real published pricing tiers.
ALTER TABLE profiles DROP CONSTRAINT IF EXISTS profiles_plan_check;
ALTER TABLE profiles ADD CONSTRAINT profiles_plan_check
  CHECK (plan IN (
    'free',
    'start','growth','scale','autonomous','enterprise',
    'agency_starter','agency_growth','agency_pro','agency_enterprise'
  ));

-- Admin-set profile allowance for enterprise accounts (NULL = not set → 1)
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS intel_profile_limit INTEGER;

-- ── Intelligence profiles ──────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS intelligence_profiles (
  id            UUID        DEFAULT uuid_generate_v4() PRIMARY KEY,
  owner_id      UUID        NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  name          TEXT        NOT NULL,
  business_name TEXT        DEFAULT '',
  notes         TEXT        DEFAULT '',
  created_at    TIMESTAMPTZ DEFAULT NOW(),
  updated_at    TIMESTAMPTZ DEFAULT NOW()
);

-- Shared access: members can be granted a role on a profile ("with the
-- right access, change the intelligence profile")
CREATE TABLE IF NOT EXISTS intelligence_profile_members (
  profile_id UUID NOT NULL REFERENCES intelligence_profiles(id) ON DELETE CASCADE,
  user_id    UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  role       TEXT NOT NULL DEFAULT 'editor' CHECK (role IN ('owner','editor','viewer')),
  created_at TIMESTAMPTZ DEFAULT NOW(),
  PRIMARY KEY (profile_id, user_id)
);

CREATE INDEX IF NOT EXISTS idx_intel_profiles_owner  ON intelligence_profiles (owner_id);
CREATE INDEX IF NOT EXISTS idx_intel_members_user    ON intelligence_profile_members (user_id);

-- ── Link Business Brain data to profiles ───────────────────────────────────
-- business_brain was project-scoped; profile scoping supersedes it (project
-- scoping remains as a fallback for accounts that haven't run this migration).
ALTER TABLE business_brain         ALTER COLUMN project_id DROP NOT NULL;
ALTER TABLE business_brain_history ALTER COLUMN project_id DROP NOT NULL;
ALTER TABLE business_brain
  ADD COLUMN IF NOT EXISTS intel_profile_id UUID REFERENCES intelligence_profiles(id) ON DELETE CASCADE;
ALTER TABLE business_brain_history
  ADD COLUMN IF NOT EXISTS intel_profile_id UUID REFERENCES intelligence_profiles(id) ON DELETE CASCADE;

-- One current-state row per profile
CREATE UNIQUE INDEX IF NOT EXISTS uq_brain_per_profile
  ON business_brain (intel_profile_id) WHERE intel_profile_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_brain_history_profile
  ON business_brain_history (intel_profile_id, created_at DESC);

-- ── Plan limit resolution + enforcement ────────────────────────────────────
CREATE OR REPLACE FUNCTION get_intel_profile_limit(uid UUID)
RETURNS INTEGER AS $$
  SELECT CASE plan
    WHEN 'agency_starter'    THEN 5
    WHEN 'agency_growth'     THEN 15
    WHEN 'agency_pro'        THEN 50
    WHEN 'agency_enterprise' THEN COALESCE(intel_profile_limit, 999999)
    WHEN 'enterprise'        THEN COALESCE(intel_profile_limit, 1)
    ELSE 1  -- free / start / growth / scale / autonomous: single-business plans
  END
  FROM profiles WHERE id = uid;
$$ LANGUAGE sql SECURITY DEFINER STABLE;

CREATE OR REPLACE FUNCTION enforce_intel_profile_limit()
RETURNS TRIGGER AS $$
DECLARE
  current_count INTEGER;
  allowed       INTEGER;
BEGIN
  SELECT COUNT(*) INTO current_count FROM intelligence_profiles WHERE owner_id = NEW.owner_id;
  allowed := COALESCE(get_intel_profile_limit(NEW.owner_id), 1);
  IF current_count >= allowed THEN
    RAISE EXCEPTION 'Intelligence profile limit reached (% of % used). Upgrade your plan to add more profiles.', current_count, allowed;
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS trg_intel_profile_limit ON intelligence_profiles;
CREATE TRIGGER trg_intel_profile_limit
  BEFORE INSERT ON intelligence_profiles
  FOR EACH ROW EXECUTE FUNCTION enforce_intel_profile_limit();

-- ── updated_at trigger ──────────────────────────────────────────────────────
CREATE OR REPLACE FUNCTION touch_intel_profile()
RETURNS TRIGGER AS $$
BEGIN NEW.updated_at = NOW(); RETURN NEW; END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_intel_profile_touch ON intelligence_profiles;
CREATE TRIGGER trg_intel_profile_touch
  BEFORE UPDATE ON intelligence_profiles
  FOR EACH ROW EXECUTE FUNCTION touch_intel_profile();

-- ── Row-Level Security ──────────────────────────────────────────────────────
ALTER TABLE intelligence_profiles        ENABLE ROW LEVEL SECURITY;
ALTER TABLE intelligence_profile_members ENABLE ROW LEVEL SECURITY;

-- Owner: full control. Members: read the profile record.
DROP POLICY IF EXISTS "ip_owner_all"    ON intelligence_profiles;
CREATE POLICY "ip_owner_all" ON intelligence_profiles
  FOR ALL USING (auth.uid() = owner_id) WITH CHECK (auth.uid() = owner_id);

DROP POLICY IF EXISTS "ip_member_read" ON intelligence_profiles;
CREATE POLICY "ip_member_read" ON intelligence_profiles
  FOR SELECT USING (
    EXISTS (SELECT 1 FROM intelligence_profile_members m
            WHERE m.profile_id = id AND m.user_id = auth.uid())
  );

-- Membership rows: profile owner manages; users see their own memberships.
DROP POLICY IF EXISTS "ipm_owner_manage" ON intelligence_profile_members;
CREATE POLICY "ipm_owner_manage" ON intelligence_profile_members
  FOR ALL USING (
    EXISTS (SELECT 1 FROM intelligence_profiles p
            WHERE p.id = profile_id AND p.owner_id = auth.uid())
  ) WITH CHECK (
    EXISTS (SELECT 1 FROM intelligence_profiles p
            WHERE p.id = profile_id AND p.owner_id = auth.uid())
  );

DROP POLICY IF EXISTS "ipm_self_read" ON intelligence_profile_members;
CREATE POLICY "ipm_self_read" ON intelligence_profile_members
  FOR SELECT USING (user_id = auth.uid());

-- ── Extend brain policies for profile members ──────────────────────────────
-- Existing policies allow auth.uid() = user_id (the writer). Add access for
-- profile owner + editors so shared profiles work.
DROP POLICY IF EXISTS "brain_profile_access" ON business_brain;
CREATE POLICY "brain_profile_access" ON business_brain
  FOR ALL USING (
    intel_profile_id IS NOT NULL AND (
      EXISTS (SELECT 1 FROM intelligence_profiles p
              WHERE p.id = intel_profile_id AND p.owner_id = auth.uid())
      OR EXISTS (SELECT 1 FROM intelligence_profile_members m
                 WHERE m.profile_id = intel_profile_id AND m.user_id = auth.uid()
                   AND m.role IN ('owner','editor'))
    )
  );

DROP POLICY IF EXISTS "brain_history_profile_access" ON business_brain_history;
CREATE POLICY "brain_history_profile_access" ON business_brain_history
  FOR ALL USING (
    intel_profile_id IS NOT NULL AND (
      EXISTS (SELECT 1 FROM intelligence_profiles p
              WHERE p.id = intel_profile_id AND p.owner_id = auth.uid())
      OR EXISTS (SELECT 1 FROM intelligence_profile_members m
                 WHERE m.profile_id = intel_profile_id AND m.user_id = auth.uid()
                   AND m.role IN ('owner','editor'))
    )
  );


-- ═══════════════════════════════════════════════════════════════════════
-- SOURCE: supabase-social-posts.sql
-- ═══════════════════════════════════════════════════════════════════════

-- Audema Social Posts — per-post data model for Social Studio (PULSE)
-- Run this in: Supabase Dashboard → SQL Editor → New query → Run
-- Requires: supabase-business-brain.sql and supabase-intelligence-profiles.sql
-- have already been run (this table uses the same dual project/profile scope).
--
-- Fixes the core architectural gap found in the social-agent audit: organic
-- posts and ad concepts were generated as one big markdown blob with no
-- per-post data model, so there was no way to approve/reject/regenerate a
-- single post, no real calendar (just a CSV with fabricated dates), and no
-- queue a future publish integration could consume. This table is that
-- missing per-post record — one row per generated post/ad variant, carrying
-- its own review status, optional scheduled time, optional rendered image,
-- and a publish_status a real platform-publish adapter can update later.

-- ── Social posts ────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS social_posts (
  id                    UUID        DEFAULT uuid_generate_v4() PRIMARY KEY,
  user_id               UUID        NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  project_id            UUID        REFERENCES projects(id) ON DELETE CASCADE,
  intel_profile_id      UUID        REFERENCES intelligence_profiles(id) ON DELETE CASCADE,

  batch_id              UUID        NOT NULL, -- groups posts generated together in one request
  source                TEXT        NOT NULL DEFAULT 'organic' CHECK (source IN ('organic', 'ad')),
  platform              TEXT        NOT NULL, -- 'LinkedIn' | 'Instagram' | 'Meta/Facebook' | 'TikTok' | 'Twitter/X' | 'Google Search' | ...
  angle_type            TEXT,       -- for ad concepts: 'pain-point' | 'offer' | 'proof' | 'urgency' | 'comparison' | 'aspirational'; null for organic

  hook                  TEXT,
  headline              TEXT        NOT NULL,
  body                  TEXT        NOT NULL DEFAULT '',
  cta                   TEXT,
  hashtags              TEXT[]      DEFAULT '{}',
  proof_point            TEXT,
  urgency_line           TEXT,
  visual_direction       TEXT,

  image_url             TEXT,       -- rendered/uploaded creative for this post
  image_render_status    TEXT        DEFAULT 'none' CHECK (image_render_status IN ('none', 'pending', 'rendered', 'failed')),

  status                TEXT        NOT NULL DEFAULT 'pending_review'
                                    CHECK (status IN ('pending_review', 'approved', 'rejected', 'scheduled', 'published', 'archived')),
  review_note            TEXT,       -- why it was rejected / regen instructions used

  scheduled_at           TIMESTAMPTZ,
  publish_status         TEXT        DEFAULT 'not_connected'
                                    CHECK (publish_status IN ('not_connected', 'queued', 'publishing', 'published', 'failed')),
  publish_platform_post_id TEXT,     -- the ID/URL the real platform API returns once published
  publish_error          TEXT,
  published_at           TIMESTAMPTZ,

  metadata               JSONB       DEFAULT '{}', -- scores, framework used, regen lineage, campaign objective, etc.

  created_at             TIMESTAMPTZ DEFAULT NOW(),
  updated_at             TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_social_posts_user       ON social_posts (user_id);
CREATE INDEX IF NOT EXISTS idx_social_posts_project    ON social_posts (project_id);
CREATE INDEX IF NOT EXISTS idx_social_posts_profile    ON social_posts (intel_profile_id);
CREATE INDEX IF NOT EXISTS idx_social_posts_batch      ON social_posts (batch_id);
CREATE INDEX IF NOT EXISTS idx_social_posts_status     ON social_posts (status);
CREATE INDEX IF NOT EXISTS idx_social_posts_scheduled  ON social_posts (scheduled_at) WHERE scheduled_at IS NOT NULL;

-- ── updated_at trigger ────────────────────────────────────────────────────
CREATE OR REPLACE FUNCTION touch_social_post()
RETURNS TRIGGER AS $$
BEGIN NEW.updated_at = NOW(); RETURN NEW; END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_social_post_touch ON social_posts;
CREATE TRIGGER trg_social_post_touch
  BEFORE UPDATE ON social_posts
  FOR EACH ROW EXECUTE FUNCTION touch_social_post();

-- ── Row-Level Security ──────────────────────────────────────────────────────
ALTER TABLE social_posts ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "social_posts_owner_all" ON social_posts;
CREATE POLICY "social_posts_owner_all" ON social_posts
  FOR ALL USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

-- Intelligence-profile editors/owners (shared access) can also manage posts
-- scoped to that profile, mirroring the business_brain sharing model.
DROP POLICY IF EXISTS "social_posts_profile_access" ON social_posts;
CREATE POLICY "social_posts_profile_access" ON social_posts
  FOR ALL USING (
    intel_profile_id IS NOT NULL AND (
      EXISTS (SELECT 1 FROM intelligence_profiles p
              WHERE p.id = intel_profile_id AND p.owner_id = auth.uid())
      OR EXISTS (SELECT 1 FROM intelligence_profile_members m
                 WHERE m.profile_id = intel_profile_id AND m.user_id = auth.uid()
                   AND m.role IN ('owner', 'editor'))
    )
  );


-- ═══════════════════════════════════════════════════════════════════════
-- SOURCE: supabase-credits.sql
-- ═══════════════════════════════════════════════════════════════════════

-- Audema Credit Balances — quota metering for paid AI generation.
-- Run this in: Supabase Dashboard → SQL Editor → New query → Run
-- Requires: supabase-intelligence-profiles.sql already run.
--
-- Starts metering api/generate-ad-image.js (real per-call OpenAI image
-- cost). Scoped per intelligence profile/site — the same dual project/
-- profile model as social_posts and business_brain — so a whole team
-- sharing a site shares one balance rather than each login getting its own.
-- New scopes default to 20,000 credits; generation pauses at 0 and the
-- caller is shown an upgrade prompt instead of a silent/opaque failure.

CREATE TABLE IF NOT EXISTS credit_balances (
  id                UUID        DEFAULT uuid_generate_v4() PRIMARY KEY,
  project_id        UUID        REFERENCES projects(id) ON DELETE CASCADE,
  intel_profile_id  UUID        REFERENCES intelligence_profiles(id) ON DELETE CASCADE,

  credits_total     INTEGER     NOT NULL DEFAULT 20000,
  credits_used      INTEGER     NOT NULL DEFAULT 0,

  created_at        TIMESTAMPTZ DEFAULT NOW(),
  updated_at        TIMESTAMPTZ DEFAULT NOW(),

  CONSTRAINT credit_balances_scope_check CHECK (project_id IS NOT NULL OR intel_profile_id IS NOT NULL),
  CONSTRAINT credit_balances_used_nonneg CHECK (credits_used >= 0)
);

-- One balance row per scope.
CREATE UNIQUE INDEX IF NOT EXISTS idx_credit_balances_profile ON credit_balances (intel_profile_id) WHERE intel_profile_id IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS idx_credit_balances_project ON credit_balances (project_id) WHERE project_id IS NOT NULL;

-- ── updated_at trigger ──────────────────────────────────────────────────────
CREATE OR REPLACE FUNCTION touch_credit_balance()
RETURNS TRIGGER AS $$
BEGIN NEW.updated_at = NOW(); RETURN NEW; END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_credit_balance_touch ON credit_balances;
CREATE TRIGGER trg_credit_balance_touch
  BEFORE UPDATE ON credit_balances
  FOR EACH ROW EXECUTE FUNCTION touch_credit_balance();

-- ── Row-Level Security ──────────────────────────────────────────────────────
-- Deductions and inserts always happen server-side via SUPABASE_SERVICE_
-- ROLE_KEY (which bypasses RLS) — api/generate-ad-image.js is the only
-- writer. The only policy needed here is read access, so the UI can show a
-- live "X credits remaining" meter without round-tripping the metered API.
ALTER TABLE credit_balances ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "credit_balances_scope_read" ON credit_balances;
CREATE POLICY "credit_balances_scope_read" ON credit_balances
  FOR SELECT USING (
    (intel_profile_id IS NOT NULL AND (
      EXISTS (SELECT 1 FROM intelligence_profiles p WHERE p.id = intel_profile_id AND p.owner_id = auth.uid())
      OR EXISTS (SELECT 1 FROM intelligence_profile_members m WHERE m.profile_id = intel_profile_id AND m.user_id = auth.uid())
    ))
    OR (project_id IS NOT NULL AND EXISTS (SELECT 1 FROM projects pr WHERE pr.id = project_id AND pr.user_id = auth.uid()))
  );


-- ═══════════════════════════════════════════════════════════════════════
-- SOURCE: supabase-audience.sql
-- ═══════════════════════════════════════════════════════════════════════

-- Audema Audience — persistent contact database + segments for campaign sending
-- Run this in: Supabase Dashboard → SQL Editor → New query → Run
-- Requires: supabase-business-brain.sql and supabase-intelligence-profiles.sql
-- have already been run (this uses the same dual project/profile scope + the
-- intelligence_profile_members sharing model as supabase-social-posts.sql).
--
-- Fixes the gap in the Pat (Email Delivery) agent: recipients previously had
-- to be pasted or imported fresh for every single campaign, with no memory of
-- who had already been contacted, who unsubscribed, or how to group people
-- into a reusable audience. This schema is that missing persistent layer:
-- one row per contact, reusable segments (dynamic tag-rules or a manually
-- curated static list), and a send log so a segment always excludes anyone
-- who has opted out or bounced.

-- ── Contacts ─────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS contacts (
  id                UUID        DEFAULT uuid_generate_v4() PRIMARY KEY,
  user_id           UUID        NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  project_id        UUID        REFERENCES projects(id) ON DELETE CASCADE,
  intel_profile_id  UUID        REFERENCES intelligence_profiles(id) ON DELETE CASCADE,

  email             TEXT        NOT NULL,
  first_name        TEXT,
  last_name         TEXT,
  company           TEXT,
  custom_fields     JSONB       NOT NULL DEFAULT '{}', -- arbitrary merge-tag values, e.g. {"city":"Melbourne"}
  tags              TEXT[]      NOT NULL DEFAULT '{}',

  status            TEXT        NOT NULL DEFAULT 'subscribed'
                                CHECK (status IN ('subscribed', 'unsubscribed', 'bounced', 'complained')),
  status_changed_at TIMESTAMPTZ,

  source            TEXT        DEFAULT 'manual', -- 'manual' | 'csv_import' | 'paste' | agent key that created it
  notes             TEXT,

  created_at        TIMESTAMPTZ DEFAULT NOW(),
  updated_at        TIMESTAMPTZ DEFAULT NOW(),

  -- One contact per email per account — segments filter this single pool
  -- rather than fragmenting the audience across projects/profiles.
  UNIQUE (user_id, email)
);

CREATE INDEX IF NOT EXISTS idx_contacts_user     ON contacts (user_id);
CREATE INDEX IF NOT EXISTS idx_contacts_project  ON contacts (project_id);
CREATE INDEX IF NOT EXISTS idx_contacts_profile  ON contacts (intel_profile_id);
CREATE INDEX IF NOT EXISTS idx_contacts_status   ON contacts (status);
CREATE INDEX IF NOT EXISTS idx_contacts_tags     ON contacts USING GIN (tags);
CREATE INDEX IF NOT EXISTS idx_contacts_email    ON contacts (lower(email));

-- ── Segments — reusable recipient groups ─────────────────────────────────────
CREATE TABLE IF NOT EXISTS segments (
  id                UUID        DEFAULT uuid_generate_v4() PRIMARY KEY,
  user_id           UUID        NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  project_id        UUID        REFERENCES projects(id) ON DELETE CASCADE,
  intel_profile_id  UUID        REFERENCES intelligence_profiles(id) ON DELETE CASCADE,

  name              TEXT        NOT NULL,
  description       TEXT,

  -- 'dynamic': membership computed at send time from filter_rules
  -- 'static':  membership is exactly the rows in segment_members
  member_mode       TEXT        NOT NULL DEFAULT 'dynamic' CHECK (member_mode IN ('dynamic', 'static')),

  -- Dynamic filter shape: { "tagsAny": ["vip"], "tagsAll": [], "status": "subscribed" }
  -- status defaults to 'subscribed' (excluding unsubscribed/bounced/complained)
  -- whenever the key is omitted — enforced in application code, not just here.
  filter_rules      JSONB       NOT NULL DEFAULT '{}',

  created_at        TIMESTAMPTZ DEFAULT NOW(),
  updated_at        TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_segments_user     ON segments (user_id);
CREATE INDEX IF NOT EXISTS idx_segments_project  ON segments (project_id);
CREATE INDEX IF NOT EXISTS idx_segments_profile  ON segments (intel_profile_id);

-- ── Static segment membership ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS segment_members (
  segment_id  UUID        NOT NULL REFERENCES segments(id) ON DELETE CASCADE,
  contact_id  UUID        NOT NULL REFERENCES contacts(id) ON DELETE CASCADE,
  added_at    TIMESTAMPTZ DEFAULT NOW(),
  PRIMARY KEY (segment_id, contact_id)
);

CREATE INDEX IF NOT EXISTS idx_segment_members_contact ON segment_members (contact_id);

-- ── Campaign send log — one row per recipient per campaign send ────────────
-- campaign_id is an opaque client-generated id (Pat's collateCampaign()), not
-- a foreign key — campaigns themselves are ephemeral/composed client-side.
CREATE TABLE IF NOT EXISTS campaign_sends (
  id             UUID        DEFAULT uuid_generate_v4() PRIMARY KEY,
  user_id        UUID        NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  contact_id     UUID        REFERENCES contacts(id) ON DELETE SET NULL,

  campaign_id    TEXT        NOT NULL,
  campaign_name  TEXT,
  segment_id     UUID        REFERENCES segments(id) ON DELETE SET NULL,

  email          TEXT        NOT NULL,
  subject        TEXT,
  status         TEXT        NOT NULL CHECK (status IN ('sent', 'failed', 'rejected')),
  provider_id    TEXT,       -- Resend email id, when sent
  error          TEXT,

  sent_at        TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_campaign_sends_user     ON campaign_sends (user_id);
CREATE INDEX IF NOT EXISTS idx_campaign_sends_contact  ON campaign_sends (contact_id);
CREATE INDEX IF NOT EXISTS idx_campaign_sends_campaign ON campaign_sends (campaign_id);

-- ── updated_at triggers ────────────────────────────────────────────────────
CREATE OR REPLACE FUNCTION touch_contact()
RETURNS TRIGGER AS $$
BEGIN NEW.updated_at = NOW(); RETURN NEW; END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_contact_touch ON contacts;
CREATE TRIGGER trg_contact_touch
  BEFORE UPDATE ON contacts
  FOR EACH ROW EXECUTE FUNCTION touch_contact();

CREATE OR REPLACE FUNCTION touch_segment()
RETURNS TRIGGER AS $$
BEGIN NEW.updated_at = NOW(); RETURN NEW; END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_segment_touch ON segments;
CREATE TRIGGER trg_segment_touch
  BEFORE UPDATE ON segments
  FOR EACH ROW EXECUTE FUNCTION touch_segment();

-- Keep status_changed_at honest whenever status actually changes.
CREATE OR REPLACE FUNCTION touch_contact_status()
RETURNS TRIGGER AS $$
BEGIN
  IF NEW.status IS DISTINCT FROM OLD.status THEN
    NEW.status_changed_at = NOW();
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_contact_status_touch ON contacts;
CREATE TRIGGER trg_contact_status_touch
  BEFORE UPDATE ON contacts
  FOR EACH ROW EXECUTE FUNCTION touch_contact_status();

-- ── Row-Level Security ──────────────────────────────────────────────────────
ALTER TABLE contacts        ENABLE ROW LEVEL SECURITY;
ALTER TABLE segments        ENABLE ROW LEVEL SECURITY;
ALTER TABLE segment_members ENABLE ROW LEVEL SECURITY;
ALTER TABLE campaign_sends  ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "contacts_owner_all" ON contacts;
CREATE POLICY "contacts_owner_all" ON contacts
  FOR ALL USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "contacts_profile_access" ON contacts;
CREATE POLICY "contacts_profile_access" ON contacts
  FOR ALL USING (
    intel_profile_id IS NOT NULL AND (
      EXISTS (SELECT 1 FROM intelligence_profiles p
              WHERE p.id = intel_profile_id AND p.owner_id = auth.uid())
      OR EXISTS (SELECT 1 FROM intelligence_profile_members m
                 WHERE m.profile_id = intel_profile_id AND m.user_id = auth.uid()
                   AND m.role IN ('owner', 'editor'))
    )
  );

DROP POLICY IF EXISTS "segments_owner_all" ON segments;
CREATE POLICY "segments_owner_all" ON segments
  FOR ALL USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "segments_profile_access" ON segments;
CREATE POLICY "segments_profile_access" ON segments
  FOR ALL USING (
    intel_profile_id IS NOT NULL AND (
      EXISTS (SELECT 1 FROM intelligence_profiles p
              WHERE p.id = intel_profile_id AND p.owner_id = auth.uid())
      OR EXISTS (SELECT 1 FROM intelligence_profile_members m
                 WHERE m.profile_id = intel_profile_id AND m.user_id = auth.uid()
                   AND m.role IN ('owner', 'editor'))
    )
  );

DROP POLICY IF EXISTS "segment_members_owner_all" ON segment_members;
CREATE POLICY "segment_members_owner_all" ON segment_members
  FOR ALL USING (
    EXISTS (SELECT 1 FROM segments s WHERE s.id = segment_id AND s.user_id = auth.uid())
  ) WITH CHECK (
    EXISTS (SELECT 1 FROM segments s WHERE s.id = segment_id AND s.user_id = auth.uid())
  );

DROP POLICY IF EXISTS "segment_members_profile_access" ON segment_members;
CREATE POLICY "segment_members_profile_access" ON segment_members
  FOR ALL USING (
    EXISTS (
      SELECT 1 FROM segments s
      WHERE s.id = segment_id AND s.intel_profile_id IS NOT NULL AND (
        EXISTS (SELECT 1 FROM intelligence_profiles p WHERE p.id = s.intel_profile_id AND p.owner_id = auth.uid())
        OR EXISTS (SELECT 1 FROM intelligence_profile_members m
                   WHERE m.profile_id = s.intel_profile_id AND m.user_id = auth.uid()
                     AND m.role IN ('owner', 'editor'))
      )
    )
  );

DROP POLICY IF EXISTS "campaign_sends_owner_all" ON campaign_sends;
CREATE POLICY "campaign_sends_owner_all" ON campaign_sends
  FOR ALL USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);


-- ═══════════════════════════════════════════════════════════════════════
-- SOURCE: supabase-audience-consent.sql
-- ═══════════════════════════════════════════════════════════════════════

-- Audema Audience — consent tracking (additive to supabase-audience.sql)
-- Run this in: Supabase Dashboard → SQL Editor → New query → Run
-- Requires: supabase-audience.sql already run.
--
-- Fixes a gap from the 2026 Agent Audit: contacts had a `source` field
-- ('manual'/'paste'/'csv_import') but no record of the actual lawful basis
-- for holding someone's email — a "how did we get permission to email this
-- person" field, not just "how did the row get typed in." This is what
-- Beeker's import flow now asks for and records per contact.

ALTER TABLE contacts ADD COLUMN IF NOT EXISTS consent_source TEXT;
ALTER TABLE contacts ADD COLUMN IF NOT EXISTS consent_timestamp TIMESTAMPTZ;

COMMENT ON COLUMN contacts.consent_source IS
  'Lawful basis / how this contact agreed to receive marketing email — e.g. "Website signup form", "Event/conference opt-in", "Existing customer", "Imported from CRM (consent verified there)". Distinct from `source`, which just tracks how the row entered this system (manual/paste/csv_import).';
COMMENT ON COLUMN contacts.consent_timestamp IS
  'When consent was given, if known. Defaults to import time when the importer does not supply an earlier date.';


-- ═══════════════════════════════════════════════════════════════════════
-- SOURCE: supabase-ab-testing.sql
-- ═══════════════════════════════════════════════════════════════════════

-- Aduma A/B Testing Schema
-- Run this in: Supabase Dashboard → SQL Editor → New query → Run
-- Or via: supabase db push

-- ── Experiments ───────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS experiments (
  id                UUID        DEFAULT gen_random_uuid() PRIMARY KEY,
  name              TEXT        NOT NULL,
  description       TEXT        DEFAULT '',
  status            TEXT        DEFAULT 'draft'
                                CHECK (status IN ('draft','active','paused','finished')),
  type              TEXT        DEFAULT 'ab'
                                CHECK (type IN ('ab','multivariate','split-url')),
  primary_goal_id   UUID,
  winner_variant_id UUID,
  start_date        TIMESTAMPTZ,
  end_date          TIMESTAMPTZ,
  created_at        TIMESTAMPTZ DEFAULT NOW(),
  updated_at        TIMESTAMPTZ DEFAULT NOW(),
  user_id           UUID        REFERENCES auth.users(id) ON DELETE SET NULL
);

-- ── Variants ──────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS variants (
  id                  UUID        DEFAULT gen_random_uuid() PRIMARY KEY,
  experiment_id       UUID        NOT NULL REFERENCES experiments(id) ON DELETE CASCADE,
  name                TEXT        NOT NULL,
  description         TEXT        DEFAULT '',
  is_control          BOOLEAN     DEFAULT FALSE,
  traffic_allocation  DECIMAL(5,2) DEFAULT 50.00,
  redirect_url        TEXT,
  changes             JSONB       DEFAULT '[]',
  created_at          TIMESTAMPTZ DEFAULT NOW()
);

-- ── Goals ─────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS goals (
  id            UUID        DEFAULT gen_random_uuid() PRIMARY KEY,
  experiment_id UUID        NOT NULL REFERENCES experiments(id) ON DELETE CASCADE,
  name          TEXT        NOT NULL,
  type          TEXT        DEFAULT 'click'
                            CHECK (type IN ('click','pageview','custom','revenue')),
  selector      TEXT,
  url_pattern   TEXT,
  is_primary    BOOLEAN     DEFAULT FALSE,
  created_at    TIMESTAMPTZ DEFAULT NOW()
);

-- ── Visitors (unique per experiment) ─────────────────────────────────────
CREATE TABLE IF NOT EXISTS visitors (
  id            UUID        DEFAULT gen_random_uuid() PRIMARY KEY,
  experiment_id UUID        NOT NULL REFERENCES experiments(id) ON DELETE CASCADE,
  variant_id    UUID        NOT NULL REFERENCES variants(id)    ON DELETE CASCADE,
  visitor_id    TEXT        NOT NULL,
  first_seen    TIMESTAMPTZ DEFAULT NOW(),
  last_seen     TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE (experiment_id, visitor_id)
);

-- ── Conversions ───────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS conversions (
  id            UUID        DEFAULT gen_random_uuid() PRIMARY KEY,
  experiment_id UUID        NOT NULL REFERENCES experiments(id) ON DELETE CASCADE,
  variant_id    UUID        NOT NULL REFERENCES variants(id)    ON DELETE CASCADE,
  goal_id       UUID        NOT NULL REFERENCES goals(id)       ON DELETE CASCADE,
  visitor_id    TEXT        NOT NULL,
  revenue       DECIMAL(10,2),
  metadata      JSONB       DEFAULT '{}',
  converted_at  TIMESTAMPTZ DEFAULT NOW()
);

-- ── Indexes ───────────────────────────────────────────────────────────────
CREATE INDEX IF NOT EXISTS idx_variants_experiment   ON variants    (experiment_id);
CREATE INDEX IF NOT EXISTS idx_goals_experiment      ON goals       (experiment_id);
CREATE INDEX IF NOT EXISTS idx_visitors_experiment   ON visitors    (experiment_id);
CREATE INDEX IF NOT EXISTS idx_visitors_id           ON visitors    (visitor_id);
CREATE INDEX IF NOT EXISTS idx_conversions_exp       ON conversions (experiment_id);
CREATE INDEX IF NOT EXISTS idx_conversions_variant   ON conversions (variant_id);
CREATE INDEX IF NOT EXISTS idx_conversions_visitor   ON conversions (visitor_id);

-- ── Row-Level Security ────────────────────────────────────────────────────
ALTER TABLE experiments ENABLE ROW LEVEL SECURITY;
ALTER TABLE variants    ENABLE ROW LEVEL SECURITY;
ALTER TABLE goals       ENABLE ROW LEVEL SECURITY;
ALTER TABLE visitors    ENABLE ROW LEVEL SECURITY;
ALTER TABLE conversions ENABLE ROW LEVEL SECURITY;

-- Service role bypasses RLS — needed for the MCP server (server-side)
-- Authenticated users see only their own experiments
CREATE POLICY "Users see own experiments"
  ON experiments FOR ALL
  USING (auth.uid() = user_id OR user_id IS NULL);

CREATE POLICY "Users see own variants"
  ON variants FOR ALL
  USING (experiment_id IN (SELECT id FROM experiments WHERE auth.uid() = user_id OR user_id IS NULL));

CREATE POLICY "Users see own goals"
  ON goals FOR ALL
  USING (experiment_id IN (SELECT id FROM experiments WHERE auth.uid() = user_id OR user_id IS NULL));

-- Tracking is write-only from the browser via anon key
CREATE POLICY "Anyone can write visitors"
  ON visitors FOR INSERT
  WITH CHECK (TRUE);

CREATE POLICY "Anyone can write conversions"
  ON conversions FOR INSERT
  WITH CHECK (TRUE);

CREATE POLICY "Service can read visitors"
  ON visitors FOR SELECT
  USING (TRUE);

CREATE POLICY "Service can read conversions"
  ON conversions FOR SELECT
  USING (TRUE);

-- ── Updated_at trigger ────────────────────────────────────────────────────
CREATE OR REPLACE FUNCTION update_updated_at()
RETURNS TRIGGER AS $$
BEGIN NEW.updated_at = NOW(); RETURN NEW; END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER experiments_updated_at
  BEFORE UPDATE ON experiments
  FOR EACH ROW EXECUTE FUNCTION update_updated_at();


-- ═══════════════════════════════════════════════════════════════════════
-- SOURCE: supabase-agent-audits.sql
-- ═══════════════════════════════════════════════════════════════════════

-- Audema Agent Audits — bi-monthly "stay current" research runs.
-- Run this in: Supabase Dashboard → SQL Editor → New query → Run
--
-- Not tenant-scoped like most other tables here — this data is about the
-- PLATFORM'S OWN agents (Rex, Pat, Beeker, Pulse, etc.), not any client's
-- business, so every signed-in user can read the same shared audit history.
-- Only api/cron-agent-audit.js (service-role key) writes to it.

CREATE TABLE IF NOT EXISTS agent_audit_runs (
  id               UUID        DEFAULT uuid_generate_v4() PRIMARY KEY,
  run_at           TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  status           TEXT        NOT NULL DEFAULT 'completed' CHECK (status IN ('completed', 'partial', 'failed')),
  agent_count      INTEGER     NOT NULL DEFAULT 0,
  flagged_count    INTEGER     NOT NULL DEFAULT 0,
  overall_summary  TEXT,
  created_at       TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS agent_audit_findings (
  id                UUID        DEFAULT uuid_generate_v4() PRIMARY KEY,
  run_id            UUID        NOT NULL REFERENCES agent_audit_runs(id) ON DELETE CASCADE,
  agent_key         TEXT        NOT NULL, -- matches AGENT_META keys in scotty.html, e.g. 'seo', 'social', 'linkedin'
  agent_label       TEXT        NOT NULL, -- human display name, e.g. "SEO Intelligence (Rex)"
  up_to_date        BOOLEAN     NOT NULL DEFAULT true,
  summary           TEXT,
  gaps              JSONB       DEFAULT '[]',   -- string[]
  recommendations   JSONB       DEFAULT '[]',   -- [{text, impact: 'high'|'medium'|'low'}]
  security_notes    JSONB       DEFAULT '[]',   -- string[]
  sources           JSONB       DEFAULT '[]',   -- [{title, url}]
  error             TEXT,                        -- set if this agent's research call failed — findings above are empty/partial in that case
  created_at        TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_agent_audit_findings_run     ON agent_audit_findings (run_id);
CREATE INDEX IF NOT EXISTS idx_agent_audit_findings_agent   ON agent_audit_findings (agent_key);
CREATE INDEX IF NOT EXISTS idx_agent_audit_runs_run_at      ON agent_audit_runs (run_at DESC);

-- ── Row-Level Security ──────────────────────────────────────────────────────
-- Read-only for any signed-in user (this is meta-info about the product's
-- own agents, not client data); writes only via the service-role key the
-- cron job uses, which bypasses RLS entirely.
ALTER TABLE agent_audit_runs ENABLE ROW LEVEL SECURITY;
ALTER TABLE agent_audit_findings ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "agent_audit_runs_read" ON agent_audit_runs;
CREATE POLICY "agent_audit_runs_read" ON agent_audit_runs
  FOR SELECT USING (auth.role() = 'authenticated');

DROP POLICY IF EXISTS "agent_audit_findings_read" ON agent_audit_findings;
CREATE POLICY "agent_audit_findings_read" ON agent_audit_findings
  FOR SELECT USING (auth.role() = 'authenticated');


-- ═══════════════════════════════════════════════════════════════════════
-- SOURCE: supabase-competitor-watch.sql
-- ═══════════════════════════════════════════════════════════════════════

-- Audema Competitor Watch — scheduled/background competitor monitoring for
-- Scout (Competitive Intel).
-- Run this in: Supabase Dashboard → SQL Editor → New query → Run
--
-- Fixes a gap flagged in the 2026 Agent Audit: Scout was fully on-demand —
-- it could research a competitor when asked, but nothing tracked change
-- over time (a real "site changed", "pricing changed" alert like Crayon or
-- Klue). This is the persistent side of that: a user opts a competitor URL
-- into tracking here, api/cron-competitor-watch.js checks it daily, and any
-- detected change (title, meta description, or page content) gets recorded.

CREATE TABLE IF NOT EXISTS competitor_watches (
  id          UUID        DEFAULT uuid_generate_v4() PRIMARY KEY,
  user_id     UUID        NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  name        TEXT        NOT NULL,
  url         TEXT        NOT NULL,
  active      BOOLEAN     NOT NULL DEFAULT true,
  created_at  TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE (user_id, url)
);

CREATE TABLE IF NOT EXISTS competitor_snapshots (
  id                UUID        DEFAULT uuid_generate_v4() PRIMARY KEY,
  watch_id          UUID        NOT NULL REFERENCES competitor_watches(id) ON DELETE CASCADE,
  title             TEXT,
  meta_description  TEXT,
  content_hash      TEXT,
  fetched_at        TIMESTAMPTZ DEFAULT NOW(),
  error             TEXT
);

CREATE TABLE IF NOT EXISTS competitor_changes (
  id              UUID        DEFAULT uuid_generate_v4() PRIMARY KEY,
  watch_id        UUID        NOT NULL REFERENCES competitor_watches(id) ON DELETE CASCADE,
  change_type     TEXT        NOT NULL CHECK (change_type IN ('title', 'meta_description', 'content')),
  previous_value  TEXT,
  new_value       TEXT,
  detected_at     TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_competitor_watches_user       ON competitor_watches (user_id);
CREATE INDEX IF NOT EXISTS idx_competitor_snapshots_watch    ON competitor_snapshots (watch_id, fetched_at DESC);
CREATE INDEX IF NOT EXISTS idx_competitor_changes_watch      ON competitor_changes (watch_id, detected_at DESC);

-- ── Row-Level Security ──────────────────────────────────────────────────────
ALTER TABLE competitor_watches   ENABLE ROW LEVEL SECURITY;
ALTER TABLE competitor_snapshots ENABLE ROW LEVEL SECURITY;
ALTER TABLE competitor_changes   ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "competitor_watches_owner_all" ON competitor_watches;
CREATE POLICY "competitor_watches_owner_all" ON competitor_watches
  FOR ALL USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "competitor_snapshots_owner_all" ON competitor_snapshots;
CREATE POLICY "competitor_snapshots_owner_all" ON competitor_snapshots
  FOR ALL USING (
    EXISTS (SELECT 1 FROM competitor_watches w WHERE w.id = watch_id AND w.user_id = auth.uid())
  );

DROP POLICY IF EXISTS "competitor_changes_owner_all" ON competitor_changes;
CREATE POLICY "competitor_changes_owner_all" ON competitor_changes
  FOR ALL USING (
    EXISTS (SELECT 1 FROM competitor_watches w WHERE w.id = watch_id AND w.user_id = auth.uid())
  );

-- Writes to snapshots/changes happen only via the service-role key
-- (api/cron-competitor-watch.js), which bypasses RLS entirely.



-- ═══════════════════════════════════════════════════════════════════════
-- SOURCE: supabase-billing.sql
-- ═══════════════════════════════════════════════════════════════════════

 this trigger, any signed-in user could set their
-- own plan/subscription_status straight through the Supabase client and grant
-- themselves a paid plan for free, or make themselves an admin. Only the
-- webhook (service_role, which bypasses RLS but NOT this trigger — it's
-- allow-listed below) and an existing admin may change these columns.
CREATE OR REPLACE FUNCTION protect_billing_columns()
RETURNS TRIGGER AS $$
BEGIN
  -- service_role = server-side calls using SUPABASE_SERVICE_ROLE_KEY (the
  -- Stripe webhook handler, admin API endpoints). auth.uid() IS NULL = a
  -- direct SQL Editor / migration run, not a PostgREST request at all.
  IF current_setting('role', true) = 'service_role' OR auth.uid() IS NULL THEN
    RETURN NEW;
  END IF;

  IF (NEW.plan                    IS DISTINCT FROM OLD.plan
      OR NEW.role                 IS DISTINCT FROM OLD.role
      OR NEW.stripe_customer_id     IS DISTINCT FROM OLD.stripe_customer_id
      OR NEW.stripe_subscription_id IS DISTINCT FROM OLD.stripe_subscription_id
      OR NEW.stripe_price_id        IS DISTINCT FROM OLD.stripe_price_id
      OR NEW.subscription_status    IS DISTINCT FROM OLD.subscription_status
      OR NEW.current_period_end     IS DISTINCT FROM OLD.current_period_end
      OR NEW.intel_profile_limit    IS DISTINCT FROM OLD.intel_profile_limit)
     AND NOT EXISTS (
       SELECT 1 FROM profiles WHERE id = auth.uid() AND role IN ('admin','super_admin')
     )
  THEN
    RAISE EXCEPTION 'Billing and role fields can only be changed by the billing system or an admin.';
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public;

DROP TRIGGER IF EXISTS trg_protect_billing_columns ON profiles;
CREATE TRIGGER trg_protect_billing_columns
  BEFORE UPDATE ON profiles
  FOR EACH ROW EXECUTE FUNCTION protect_billing_columns();

-- DONE! profiles now carries real Stripe subscription state, every webhook
-- event is logged to billing_events, and none of it is client-writable.
