#!/usr/bin/env python3
"""
Build supabase-install-all.sql from the individual migration files.

The installer's own header has always said it is "generated by concatenating
them and patching in idempotency guards, not hand-maintained separately" —
but the thing that generated it lived nowhere. So the one file every operator
actually runs was, in practice, edited by hand and hoped to still match its
sources. This is the generator, in the repository, so it does.

Two rules it enforces:

  Order is dependency order. profiles and auth.users have to exist before
  anything references them, so SOURCES below is a list, not a directory scan.

  Every CREATE POLICY and CREATE TRIGGER gets a DROP ... IF EXISTS in front
  of it. CREATE TABLE/INDEX already carry IF NOT EXISTS; policies and
  triggers have no such form, and without the drop, re-running the installer
  fails with 42710 "already exists" partway through — leaving the database
  half-migrated, which is the worst of the available outcomes.

  The source files now carry their own guards too, so each is re-runnable on
  its own. This step is idempotent: a guard already present is not doubled.

Usage:
    python3 scripts/build-install-all.py            # write the file
    python3 scripts/build-install-all.py --check    # verify it is current
"""

import os
import re
import sys

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(REPO, 'supabase-install-all.sql')

# Dependency order. Base schema first; everything else builds on profiles.
SOURCES = [
    'database/supabase-schema.sql',
    'database/admin-setup.sql',
    'supabase-business-brain.sql',
    'supabase-intelligence-profiles.sql',
    'supabase-social-posts.sql',
    'supabase-credits.sql',
    'supabase-audience.sql',
    'supabase-audience-consent.sql',
    'supabase-ab-testing.sql',
    'supabase-agent-audits.sql',
    'supabase-competitor-watch.sql',
    'supabase-analytics-brain.sql',
    'supabase-nancy.sql',
    'supabase-seo-pipeline.sql',
    'supabase-billing.sql',
    'supabase-grants.sql',
    'supabase-mission-usage.sql',
    'supabase-support.sql',
    'supabase-email-events.sql',
    'supabase-email-engine.sql',
    'supabase-email-suppression.sql',
    'supabase-competitive-roster.sql',
    'supabase-video-gallery.sql',
    'supabase-cro-backlog.sql',
    'supabase-system-failures.sql',
]

POLICY_1 = re.compile(r'(?m)^CREATE POLICY ("([^"]+)"|(\S+)) ON (\w+)')
POLICY_2 = re.compile(r'(?m)^CREATE POLICY ("([^"]+)"|(\S+))\s*\n\s*ON (\w+)')
TRIGGER_1 = re.compile(r'(?m)^CREATE TRIGGER (\w+)[^\n]*\bON (\w+)')
TRIGGER_2 = re.compile(r'(?m)^CREATE TRIGGER (\w+)\s*\n\s*(?:BEFORE|AFTER|INSTEAD OF)[^\n]*\bON (\w+)')


def guard(sql: str) -> str:
    """Put a DROP ... IF EXISTS in front of every unguarded policy/trigger."""
    for pat, kind in ((POLICY_1, 'POLICY'), (POLICY_2, 'POLICY'),
                      (TRIGGER_1, 'TRIGGER'), (TRIGGER_2, 'TRIGGER')):
        out, last = [], 0
        for m in pat.finditer(sql):
            if kind == 'POLICY':
                name = m.group(2) or m.group(3)
                quoted = '"%s"' % name if m.group(2) else name
                table = m.group(4)
            else:
                name = quoted = m.group(1)
                table = m.group(2)
            # Already guarded? Leave it be — this must be safe to run twice.
            if 'DROP %s IF EXISTS' % kind in sql[max(0, m.start() - 160):m.start()]:
                continue
            out.append(sql[last:m.start()])
            out.append('DROP %s IF EXISTS %s ON %s;\n' % (kind, quoted, table))
            last = m.start()
        out.append(sql[last:])
        sql = ''.join(out)
    return sql


def build() -> str:
    bar = '-- ' + '═' * 71
    parts = [
        bar,
        '-- Audema — Full Database Install (idempotent, safe to re-run)',
        bar,
        '-- Run this ONCE in: Supabase Dashboard → SQL Editor → New query → Run.',
        '--',
        '-- GENERATED FILE — do not edit by hand.',
        '--   Edit the source file, then: python3 scripts/build-install-all.py',
        '--',
        '-- Every CREATE TABLE/INDEX uses IF NOT EXISTS; every CREATE POLICY and',
        '-- CREATE TRIGGER has a matching DROP ... IF EXISTS patched in ahead of it.',
        '-- Running this against a database that already has some or all of these',
        '-- objects will not raise "already exists" — it redefines them and moves on.',
        '--',
        '-- It drops no table and deletes no data. It creates missing',
        '-- tables/columns/indexes and replaces policy/trigger/function definitions.',
        '--',
        '-- Source files, in dependency order (each remains the source of truth):',
        '--',
    ]
    parts += ['--   %s' % s for s in SOURCES]
    parts += [bar, '', '']

    for src in SOURCES:
        path = os.path.join(REPO, src)
        if not os.path.exists(path):
            sys.stderr.write('missing source: %s\n' % src)
            sys.exit(1)
        with open(path, encoding='utf-8') as fh:
            body = fh.read().rstrip('\n')
        parts += [bar, '-- SOURCE: %s' % src, bar, '', guard(body), '', '']

    return '\n'.join(parts).rstrip('\n') + '\n'


if __name__ == '__main__':
    generated = build()
    if '--check' in sys.argv:
        current = open(OUT, encoding='utf-8').read() if os.path.exists(OUT) else ''
        if current != generated:
            sys.stderr.write(
                'supabase-install-all.sql is out of date.\n'
                'Run: python3 scripts/build-install-all.py\n')
            sys.exit(1)
        print('supabase-install-all.sql is up to date')
    else:
        with open(OUT, 'w', encoding='utf-8') as fh:
            fh.write(generated)
        print('wrote %s (%d lines from %d sources)'
              % (OUT, generated.count('\n') + 1, len(SOURCES)))
