/**
 * api/ab-track.js — A/B Test Event Ingest
 *
 * Receives visitor assignments and conversion events from the tracking snippet.
 * Called by the browser with keepalive: true so it fires even on page unload.
 *
 * POST {
 *   type:         'visit' | 'convert',
 *   experimentId: string,
 *   variantId:    string,
 *   visitorId:    string,
 *   goalId?:      string,   // required for type='convert'
 *   metadata?:    object,
 *   revenue?:     number,
 * }
 *
 * Required env vars:
 *   SUPABASE_URL              — Supabase project URL
 *   SUPABASE_SERVICE_ROLE_KEY — service-role key
 */

'use strict';

async function sb(env, method, path, body, prefer) {
  const res = await fetch(`${env.SUPABASE_URL}/rest/v1${path}`, {
    method,
    headers: {
      'apikey':        env.SUPABASE_SERVICE_ROLE_KEY,
      'Authorization': `Bearer ${env.SUPABASE_SERVICE_ROLE_KEY}`,
      'Content-Type':  'application/json',
      'Prefer':        prefer || 'return=minimal',
    },
    body: body ? JSON.stringify(body) : undefined,
    signal: AbortSignal.timeout(8000),
  });
  return { ok: res.ok, status: res.status };
}

/** GET returning parsed rows, or null on any failure. */
async function sbGet(env, path) {
  try {
    const res = await fetch(`${env.SUPABASE_URL}/rest/v1${path}`, {
      headers: {
        'apikey':        env.SUPABASE_SERVICE_ROLE_KEY,
        'Authorization': `Bearer ${env.SUPABASE_SERVICE_ROLE_KEY}`,
      },
      signal: AbortSignal.timeout(8000),
    });
    if (!res.ok) return null;
    return await res.json();
  } catch { return null; }
}

const UUID_RE = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;

/** Largest metadata blob accepted on one conversion, serialised. */
const MAX_METADATA_BYTES = 4096;

/**
 * metadata is a free-form jsonb column filled from an unauthenticated request
 * body, so it is the one field here with no shape to validate against. Cap
 * what a single event can store; an oversized blob is dropped, not truncated,
 * because half a JSON object is not more truthful than none.
 */
function boundedMetadata(value) {
  if (!value || typeof value !== 'object' || Array.isArray(value)) return {};
  try {
    const json = JSON.stringify(value);
    return json.length > MAX_METADATA_BYTES ? {} : value;
  } catch { return {}; }
}

/**
 * Does this event describe a test that is actually running, with a variant
 * and goal that actually belong to it?
 *
 * This endpoint is deliberately open — the tracking snippet runs on the
 * customer's own public pages, so it cannot carry a secret, and anybody who
 * views the source of one of those pages learns the experiment and variant
 * ids. Without this check, that reader could POST visits and conversions
 * naming any variant id they liked, including one from a different customer's
 * experiment, and shift the conversion rate the customer bases a decision on.
 *
 * Three things are checked, none of which a legitimate snippet can fail:
 *   - the variant belongs to the named experiment (no cross-experiment writes)
 *   - the goal belongs to the named experiment (same, for conversions)
 *   - the experiment is 'active' (a finished test cannot be re-scored after
 *     the customer has read its result)
 *
 * Fails closed: if the lookup cannot be completed, the event is dropped
 * rather than written unverified.
 */
async function eventIsCoherent(env, { experimentId, variantId, goalId }) {
  const experiments = await sbGet(env,
    `/experiments?id=eq.${experimentId}&select=id,status&limit=1`);
  if (!experiments || !experiments.length) return false;
  if (experiments[0].status !== 'active') return false;

  const variants = await sbGet(env,
    `/variants?id=eq.${variantId}&experiment_id=eq.${experimentId}&select=id&limit=1`);
  if (!variants || !variants.length) return false;

  if (goalId) {
    const goals = await sbGet(env,
      `/goals?id=eq.${goalId}&experiment_id=eq.${experimentId}&select=id&limit=1`);
    if (!goals || !goals.length) return false;
  }
  return true;
}

module.exports = async function handler(req, res) {
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'POST, OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type');
  if (req.method === 'OPTIONS') return res.status(200).end();
  if (req.method !== 'POST') return res.status(405).end();

  const { type, experimentId, variantId, visitorId, goalId, metadata, revenue } = req.body || {};
  if (!type || !experimentId || !variantId || !visitorId) return res.status(400).end();

  // Ids go straight into PostgREST filter expressions below. Anything that is
  // not a uuid is rejected here rather than interpolated into a query string.
  if (!UUID_RE.test(String(experimentId)) || !UUID_RE.test(String(variantId))) return res.status(400).end();
  if (goalId && !UUID_RE.test(String(goalId))) return res.status(400).end();

  // visitor_id is generated by the snippet and is free text, so it is bounded
  // rather than pattern-matched — an unbounded value is a storage abuse vector.
  if (typeof visitorId !== 'string' || visitorId.length > 128) return res.status(400).end();

  const env = {
    SUPABASE_URL:              process.env.SUPABASE_URL,
    SUPABASE_SERVICE_ROLE_KEY: process.env.SUPABASE_SERVICE_ROLE_KEY,
  };
  if (!env.SUPABASE_URL || !env.SUPABASE_SERVICE_ROLE_KEY) return res.status(500).end();

  try {
    if (type !== 'visit' && type !== 'convert') return res.status(400).end();
    if (type === 'convert' && !goalId) return res.status(400).end();

    if (!await eventIsCoherent(env, { experimentId, variantId, goalId })) {
      // Silently dropped: an event naming a variant that is not part of this
      // experiment, or a test that is not running, is not a result.
      return res.status(204).end();
    }

    if (type === 'visit') {
      // One row per (experiment, visitor) — the table's UNIQUE constraint.
      // merge-duplicates makes the repeat pageviews of a returning visitor
      // refresh last_seen instead of failing, and keeps the variant they were
      // first bucketed into rather than letting a later request reassign them.
      await sb(env, 'POST', '/visitors', {
        experiment_id: experimentId,
        variant_id:    variantId,
        visitor_id:    visitorId,
        last_seen:     new Date().toISOString(),
      }, 'return=minimal,resolution=ignore-duplicates');

      await fetch(`${env.SUPABASE_URL}/rest/v1/visitors` +
        `?experiment_id=eq.${encodeURIComponent(experimentId)}` +
        `&visitor_id=eq.${encodeURIComponent(visitorId)}`, {
        method: 'PATCH',
        headers: {
          'apikey':        env.SUPABASE_SERVICE_ROLE_KEY,
          'Authorization': `Bearer ${env.SUPABASE_SERVICE_ROLE_KEY}`,
          'Content-Type':  'application/json',
          'Prefer':        'return=minimal',
        },
        body: JSON.stringify({ last_seen: new Date().toISOString() }),
        signal: AbortSignal.timeout(5000),
      }).catch(() => {});
    }

    if (type === 'convert') {
      // A conversion is one visitor completing one goal once. The unique
      // index on (experiment_id, visitor_id, goal_id) enforces it; a repeat
      // collides there and is ignored rather than inflating the count.
      const rev = Number(revenue);
      await sb(env, 'POST', '/conversions', {
        experiment_id: experimentId,
        variant_id:    variantId,
        goal_id:       goalId,
        visitor_id:    visitorId,
        revenue:       Number.isFinite(rev) && rev >= 0 ? rev : null,
        metadata:      boundedMetadata(metadata),
        converted_at:  new Date().toISOString(),
      }, 'return=minimal,resolution=ignore-duplicates');
    }

    return res.status(204).end();
  } catch {
    return res.status(204).end(); // Always 204 — don't break the user's page
  }
};
